terraform {
  required_providers {
    random = {
      source  = "hashicorp/random"
      version = "1.3.1"
    }
  }
  required_version = ">= 0.13"
}

provider "random" {
  # random provider is "logical" and needs no config for typical use
}

resource "random_password" "example" {
  length           = 16
  override_special = "!@#"
  keepers = {
    # keepers let you re-create only when inputs change
    project = "random-demo"
  }
}

output "password" {
  value       = random_password.example.result
  description = "Random password generated by the random provider"
  sensitive   = true
}
